version: '3'
services: 
  sibaku-web:
    container_name: sibaku_web
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - "3000:80"